#!/usr/bin/python2.7
# -*- coding: utf-8 -*-

import os
import sys
import time
import json
import shutil
import requests
import tempfile
import os.path
import argparse
import subprocess

class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'

def exit(retValue=0):
    if retValue is 0:
        print bcolors.OKBLUE + '[*] Exiting... Bye \\o/' + bcolors.ENDC
    else:
        print bcolors.FAIL + '[-] Exiting with erros :(' + bcolors.ENDC

    sys.exit(retValue)

def hasSatisfiedDependencies():
    flag = True
    
    sys.stdout.write('[*] Checking dependencies...\n')
    # Check Frida
    try:
        subprocess.check_output(['frida', '--version'])
    except:
        flag = False
        sys.stdout.write(bcolors.FAIL + '[-] Failed. frida is not installed\n' + bcolors.ENDC)

    # Check aapt
    try:
        subprocess.check_output(['aapt', 'version'])
    except:
        flag = False
        sys.stdout.write(bcolors.FAIL + '[-] Failed. aapt is not installed\n' + bcolors.ENDC)

    # Check apktool
    try:
        subprocess.check_output(['apktool', '--version'])
    except:
        flag = False
        sys.stdout.write(bcolors.FAIL + '[-] Failed. apktool is not installed\n' + bcolors.ENDC)

    # Check unxz
    try:
        subprocess.check_output(['unxz', '--version'])
    except:
        flag = False
        sys.stdout.write(bcolors.FAIL + '[-] Failed. unxz is not installed\n' + bcolors.ENDC)

    if 'zip alignment' not in subprocess.check_output(['zipalign;echo'], stderr=subprocess.STDOUT, shell=True).lower():
        flag = False
        sys.stdout.write(bcolors.FAIL + '[-] Failed. zipalign is not installed\n' + bcolors.ENDC)

    return flag

def updateFridaGadgets():
    if not hasSatisfiedDependencies():
        exit(1)

    sys.stdout.write('[+] Updating frida gadgets\n')
    fridaVersion = subprocess.check_output(['frida', '--version']).strip()
    sys.stdout.write('[*] Frida version: ' + fridaVersion + '\n')

    githubLink = 'https://api.github.com/repos/frida/frida/releases'

    response = requests.get(githubLink).text
    releases = json.loads(response)

    releaseLink = None

    for release in releases:
        if release['tag_name'] == fridaVersion:
            releaseLink = release['url']
            break
    
    response = requests.get(releaseLink).text
    releaseContent = json.loads(response)

    assets = releaseContent['assets']

    listGadgets = []
    for asset in assets:
        if 'gadget' in asset['name'] and 'android' in asset['name']:
            gadget = {}
            gadget['name'] = asset['name']
            gadget['url'] = asset['browser_download_url']

            listGadgets.append(gadget)
    
    currentFolder = os.path.dirname(os.path.abspath(__file__))
    gadgetsFolder = os.path.join(currentFolder, 'gadgets')
    targetFolder = os.path.join(gadgetsFolder, fridaVersion)

    if not os.path.isdir(targetFolder):
        os.makedirs(targetFolder)

    downloadedFiles = []
    for gadget in listGadgets:
        gadgetFilePath = os.path.join(targetFolder, gadget['name'])

        if os.path.isfile(gadgetFilePath.replace('.xz', '')):
            sys.stdout.write('[*] %s already exists. Skipping.\n' %(gadget['name']))
        else:
            download(gadget['url'], gadgetFilePath)
            downloadedFiles.append(gadgetFilePath)

    sys.stdout.write('[*] Extracting downloaded files...\n')

    for downloadedFile in downloadedFiles:
        subprocess.check_output(['unxz', downloadedFile])

    sys.stdout.write('[*] Done!\n')
    
def download(url, targetPath):
    fileName = targetPath.split('/')[-1]
    response = requests.get(url, stream=True)
    totalLength = response.headers.get('content-length')
    totalLength = int(totalLength)
    

    with open(targetPath, 'wb') as f:
        downloaded = 0
        
        sys.stdout.write('\r[+] Downloading %s - 000 %%' %(fileName))
        sys.stdout.flush()

        for chunk in response.iter_content(chunk_size=1024):
            if chunk:
                downloaded += len(chunk)
                percentage = int(downloaded * 100 / totalLength)
        
                sys.stdout.write('\r[+] Downloading %s - %03d %%' %(fileName, percentage))
                sys.stdout.flush()
                f.write(chunk)

    sys.stdout.write('\n')


def patchApk(apkFile, fridaGadgetFile, configFile, autoloadScript):
    if not os.path.isfile(apkFile):
        sys.stdout.write(bcolors.FAIL + '[-] The specified APK does not exist.\n' + bcolors.ENDC)
        exit(1)
        
    if not os.path.isfile(fridaGadgetFile):
        print fridaGadgetFile
        sys.stdout.write(bcolors.FAIL + '[-] The specified frida-gadget file does not exist.\n' + bcolors.ENDC)
        exit(1)

    if configFile and not os.path.isfile(configFile):
        sys.stdout.write(bcolors.FAIL + '[-] The specified config file does not exist.\n' + bcolors.ENDC)
        exit(1)

    if autoloadScript and not os.path.isfile(autoloadScript):
        sys.stdout.write(bcolors.FAIL + '[-] The specified autoload hook file does not exist.\n' + bcolors.ENDC)
        exit(1)
        
    tmpDir = tempfile.gettempdir()
    tmpDirPatcher = os.path.join(tmpDir, 'apkpatcher_tmp')

    if os.path.isdir(tmpDirPatcher):
        shutil.rmtree(tmpDirPatcher)
    
    tmpDirApk = os.path.join(tmpDirPatcher, apkFile.replace('.apk', '').replace('.', '_'))
    os.makedirs(tmpDirPatcher)

    sys.stdout.write('[+] Extracting %s\n' %(apkFile))
    subprocess.check_output(['apktool', 'd', '-o', tmpDirApk, apkFile, '-f'])
    
    permissions = subprocess.check_output(['aapt', 'dump', 'permissions', apkFile])

    if 'android.permission.INTERNET' not in permissions:
        patchManifest(tmpDirApk)

    dumpLines = subprocess.check_output(['aapt', 'dump', 'badging', apkFile]).split('\n')

    entryPoint = None

    for line in dumpLines:
        if 'launchable-activity:' in line:
            nameStart = line.find('name=')
            entryPoint = line[nameStart:].split(' ')[0].replace('name=', '').replace('\'', '').replace('"', '')
            break

    if entryPoint is None:
        sys.stdout.write('[-] Something was wrong while getting launchable-activity\n')
        exit(1)

    sys.stdout.write('[*] Entrypoint is %s\n' %(entryPoint))

    entryPointPath = None
    listFilesTmpApkDir = os.listdir(tmpDirApk)

    for entry in listFilesTmpApkDir:
        if entry.startswith('smali'):
            entryPointPathAux = os.path.join(tmpDirApk, entry, entryPoint.replace('.', '/') + '.smali')
    
            if os.path.isfile(entryPointPathAux):
                entryPointPath = entryPointPathAux
                sys.stdout.write('[*] Found entrypoint at %s\n' %(entryPointPath.replace(tmpDirApk, '')))
                break

    if entryPointPath is None:
        sys.stdout.write('[-] Could not find the entrypoint\n')
        sys.exit(1)

    patchEntryPoint(entryPointPath)
    insertGadgetLib(tmpDirApk, fridaGadgetFile, configFile, autoloadScript)

    newFileName, targetFile = repackageApk(tmpDirApk, apkFile)
    signAndZipAlignApk(targetFile)
    
    print bcolors.OKBLUE + '[*] Done!' + bcolors.ENDC
    print bcolors.OKBLUE + '[*] Your patched file is %s' %(targetFile) + bcolors.ENDC


def signAndZipAlignApk(targetFile):
    # Generatey a key
    
    sys.stdout.write('[*] Generating a random key...\n')
    subprocess.call('keytool -genkey -keyalg RSA -keysize 2048 -validity 700 -noprompt -alias apkpatcheralias1 -dname "CN=apk.patcher.com, OU=ID, O=APK, L=Patcher, S=Patch, C=BR" -keystore apkpatcherkeystore -storepass password -keypass password', shell=True)

    sys.stdout.write('[*] Signing the patched apk...\n')
    subprocess.call('jarsigner -sigalg SHA1withRSA -digestalg SHA1 -keystore apkpatcherkeystore -storepass password %s apkpatcheralias1 >/dev/null 2>&1' %(targetFile), shell=True)
    os.remove('apkpatcherkeystore')

    sys.stdout.write('[*] The apk was signed.\n')
    sys.stdout.write('[*] Optimizing apk (zipalign)...\n')
    
    tmpTargetFile = targetFile.replace('.apk', '_tmp.apk')
    shutil.move(targetFile, tmpTargetFile)

    subprocess.call('zipalign 4 %s %s' %(tmpTargetFile, targetFile), stderr=subprocess.STDOUT, shell=True)
    os.remove(tmpTargetFile)

    sys.stdout.write('[*] The file was optimized.\n')

def repackageApk(tmpDirApk, apkFile):
    workingDirectory = os.getcwd()
    newFileName = apkFile.replace('.apk', '_patched.apk')
    
    targetFile = os.path.join(workingDirectory, newFileName)

    if os.path.isfile(targetFile): # ORLY?
        safeName = str(time.time()).replace('.', '')
        newFileName = apkFile.replace('.apk', '_%s_patched.apk' %(safeName))

        targetFile = os.path.join(workingDirectory, newFileName)


    sys.stdout.write('[*] Repackaging your apk. This can take some time...\n')
    subprocess.check_output(['apktool', 'b', '-o', targetFile, tmpDirApk])

    return (newFileName, targetFile)

def patchEntryPoint(entryPointPath):
    fridaGadgetString = '''
    const-string v0, "frida-gadget"

    invoke-static {v0}, Ljava/lang/System;->loadLibrary(Ljava/lang/String;)V

'''

    fullGadgetMethod = '''
.method static constructor <clinit>()V
    .locals 1

    .prologue
    const-string v0, "frida-gadget"

    invoke-static {v0}, Ljava/lang/System;->loadLibrary(Ljava/lang/String;)V

    return-void
.end method
'''

    f = open(entryPointPath, 'r')
    content = f.read()
    f.close()

    if 'frida-gadget' in content:
        sys.stdout.write('[*] The frida-gadget is already in the entrypoint.\n')
        return

    directMethodsStartIndex = content.find('# direct methods')
    directMethodsEndIndex = content.find('# virtual methods')

    if directMethodsStartIndex is -1 or directMethodsEndIndex is -1:
        sys.stdout.write('[-] Could not find direct methods.\n')
        exit(1)

    classConstructorStartIndex = content.find('.method static constructor <clinit>()V',
            directMethodsStartIndex, directMethodsEndIndex)

    if classConstructorStartIndex is -1:
        hasClassConstructor = False
    else:
        hasClassConstructor = True

    if hasClassConstructor:
        classConstructorEndIndex = content.find('.end method',
            classConstructorStartIndex, directMethodsEndIndex)

    if hasClassConstructor and classConstructorEndIndex is -1:
        sys.stdout.write('[-] Could not find the end of class constructor.\n')
        exit(1)

    if hasClassConstructor:
        prologueStartIndex = content.find('.prologue',
                classConstructorStartIndex, classConstructorEndIndex)

    if hasClassConstructor and prologueStartIndex is -1:
        sys.stdout.write('[-] Could not find the .prologue of class constructor.\n')
        exit(1)

    if hasClassConstructor and prologueStartIndex > -1:
        prologueEndIndex = prologueStartIndex + len('.prologue') + 1


    if hasClassConstructor:
        newContent = content[0:prologueEndIndex]
        newContent += fridaGadgetString
        newContent += content[prologueEndIndex:]
    else:
        tmpIndex = directMethodsStartIndex + len('# direct methods') + 1
        newContent = content[0:tmpIndex]
        newContent += fullGadgetMethod
        newContent += content[tmpIndex:]


    # The newContent is ready to be saved

    f = open(entryPointPath, 'w')
    f.write(newContent)
    f.close()

    sys.stdout.write('[+] The entrypoint was patched!\n')

def deleteExistingGadget(gadgetFolderPath):
    listFiles = os.listdir(gadgetFolderPath)

    if 'libfrida-gadget.so' in listFiles:
        sys.stdout.write('[!] I found an existing libfrida-gadget.so here.\n')
        sys.stdout.write('[!] I will delete it and put an updated version of gadget.\n')

        fileToDelete = os.path.join(gadgetFolderPath, 'libfrida-gadget.so')
        os.remove(filetoDelete)

    if 'libfrida-gadget.config' in listFiles:
        sys.stdout.write('[!] I found an existing libfrida-gadget.config here.\n')
        sys.stdout.write('[!] I will delete it and put an updated version of gadget.\n')

        fileToDelete = os.path.join(gadgetFolderPath, 'libfrida-gadget.config')
        os.remove(filetoDelete)
        

def insertGadgetLib(tmpDirApk, fridaGadgetFile, configFile, autoloadScript):
    libsPath = os.path.join(tmpDirApk, 'lib/')

    if not os.path.isdir(libsPath):
        sys.stdout.write('[+] Creating libs folder.\n')
        os.makedirs(libsPath)

    if 'arm' in fridaGadgetFile and not '64' in fridaGadgetFile:
        targetLibPath1 = os.path.join(libsPath, 'armeabi')
        targetLibPath2 = os.path.join(libsPath, 'armeabi-v7a')

        if not os.path.isdir(targetLibPath1):
            sys.stdout.write('[+] Creating armeabi folder.\n')
            os.makedirs(targetLibPath1)

        deleteExistingGadget(targetLibPath1)

        if not os.path.isdir(targetLibPath2):
            sys.stdout.write('[+] Creating armeabi-v7a folder.\n')
            os.makedirs(targetLibPath2)

        deleteExistingGadget(targetLibPath2)

        targetFilePath1 = os.path.join(targetLibPath1, 'libfrida-gadget.so')
        targetFilePath2 = os.path.join(targetLibPath2, 'libfrida-gadget.so')

        sys.stdout.write('[+] Copying frida-gadget to libs folder.\n')
        shutil.copyfile(fridaGadgetFile, targetFilePath1)
        shutil.copyfile(fridaGadgetFile, targetFilePath2)

        if configFile:
            sys.stdout.write('[+] Copying config file to libs folder.\n')
            shutil.copyfile(configFile, targetFilePath1.replace('.so', '.config.so'))
            shutil.copyfile(configFile, targetFilePath2.replace('.so', '.config.so'))
        
        if autoloadScript:
            sys.stdout.write('[+] Copying autoload script to libs folder.\n')
            shutil.copyfile(autoloadScript, targetFilePath1.replace('libfrida-gadget.so', 'libhook.js.so'))
            shutil.copyfile(autoloadScript, targetFilePath2.replace('libfrida-gadget.so', 'libhook.js.so'))

            
    elif 'arm64' in fridaGadgetFile:
        targetLibPath = os.path.join(libsPath, 'arm64-v8a')

        if not os.path.isdir(targetLibPath):
            sys.stdout.write('[+] Creating arm64-v8a folder.\n')
            os.makedirs(targetLibPath)

        deleteExistingGadget(targetLibPath)

        targetFilePath = os.path.join(targetLibPath, 'libfrida-gadget.so')

        sys.stdout.write('[+] Copying frida-gadget to libs folder.\n')
        shutil.copyfile(fridaGadgetFile, targetFilePath)

        if configFile:
            sys.stdout.write('[+] Copying config file to libs folder.\n')
            shutil.copyfile(configFile, targetFilePath.replace('.so', '.config.so'))
        
        if autoloadScript:
            sys.stdout.write('[+] Copying autoload script to libs folder.\n')
            shutil.copyfile(autoloadScript, targetFilePath.replace('libfrida-gadget.so', 'libhook.js.so'))

        
    elif 'i386' in fridaGadgetFile or ('x86' in fridaGadgetFile and not '64' in fridaGadgetFile):
        targetLibPath = os.path.join(libsPath, 'x86')

        if not os.path.isdir(targetLibPath):
            sys.stdout.write('[+] Creating x86 folder.\n')
            os.makedirs(targetLibPath)

        deleteExistingGadget(targetLibPath)

        targetFilePath = os.path.join(targetLibPath, 'libfrida-gadget.so')

        sys.stdout.write('[+] Copying frida-gadget to libs folder.\n')
        shutil.copyfile(fridaGadgetFile, targetFilePath)

        if configFile:
            sys.stdout.write('[+] Copying config file to libs folder.\n')
            shutil.copyfile(configFile, targetFilePath.replace('.so', '.config.so'))
        
        if autoloadScript:
            sys.stdout.write('[+] Copying autoload script to libs folder.\n')
            shutil.copyfile(autoloadScript, targetFilePath.replace('libfrida-gadget.so', 'libhook.js.so'))

        
    elif 'x86_64' in fridaGadgetFile:
        targetLibPath = os.path.join(libsPath, 'x86_64')

        if not os.path.isdir(targetLibPath):
            sys.stdout.write('[+] Creating x86_64 folder.\n')
            os.makedirs(targetLibPath)

        deleteExistingGadget(targetLibPath)

        targetFilePath = os.path.join(targetLibPath, 'libfrida-gadget.so')

        sys.stdout.write('[+] Copying frida-gadget to libs folder.\n')
        shutil.copyfile(fridaGadgetFile, targetFilePath)

        if configFile:
            sys.stdout.write('[+] Copying config file to libs folder.\n')
            shutil.copyfile(configFile, targetFilePath.replace('.so', '.config.so'))
        
        if autoloadScript:
            sys.stdout.write('[+] Copying autoload script to libs folder.\n')
            shutil.copyfile(autoloadScript, targetFilePath.replace('libfrida-gadget.so', 'libhook.js.so'))
        
        
    else:
        sys.stdout.write('[-] Could not identify the right folder to put the gadget.\n')
        sys.stdout.write('[-] Please rename your frida-gadget file with architecture information.\n')
        exit(1)

    sys.stdout.write('[*] The gadget file was inserted.\n')


def patchManifest(tmpDirApk):
    sys.stdout.write('[+] Patching AndroidManifest.xml...\n')

    internetPermissionTag = '<uses-permission android:name="android.permission.INTERNET"/>'
    manifestPath = os.path.join(tmpDirApk, 'AndroidManifest.xml')
    f = open(manifestPath, 'r')
    manifest = f.read()
    f.close()

    startManifestTag = manifest.find('<manifest ')

    if startManifestTag is -1:
        sys.stdout.write('[-] Something is wrong with AndroidManifest.xml\n')
        exit(1)

    endManifestTag = manifest.find('>', startManifestTag)

    if endManifestTag is -1:
        sys.stdout.write('[-] Something is wrong with AndroidManifest.xml\n')
        exit(1)

    newManifest = manifest[:endManifestTag+1] + '\n'
    newManifest += '    '  # indent
    newManifest += internetPermissionTag
    newManifest += manifest[endManifestTag+1:]
    
    f = open(manifestPath, 'w')
    f.write(newManifest)
    f.close()

def getRecommendedGadget():
    ret = None

    sys.stdout.write('[*] Trying to identify the right frida-gadget...\n')
    sys.stdout.write('[*] Waiting for device...\n')
    os.system('adb wait-for-device')
    abi = subprocess.check_output(['adb', 'shell', 'getprop ro.product.cpu.abi']).strip()

    sys.stdout.write('[*] The abi is %s\n' %(abi))
    
    fridaVersion = subprocess.check_output(['frida', '--version']).strip()
    currentFolder = os.path.dirname(os.path.abspath(__file__))                                                                             
    gadgetsFolder = os.path.join(currentFolder, 'gadgets')
    targetFolder = os.path.join(gadgetsFolder, fridaVersion)
    
    if os.path.isdir(targetFolder):
        dirList = os.listdir(targetFolder)
        gadgetFiles = [f for f in dirList if os.path.isfile(os.path.join(targetFolder, f))]
    else:
        sys.stdout.write('[-] Gadget folder not found. Try "python %s --update"\n' %(sys.argv[0]))
        return ret

    if abi in ['armeabi', 'armeabi-v7a']:
        for gadgetFile in gadgetFiles:
            if 'arm' in gadgetFile and not '64' in gadgetFile:
                fullPath = os.path.join(targetFolder, gadgetFile)
                ret = fullPath
                break

    elif abi is 'arm64-v8a' or 'arm64' in abi:
        for gadgetFile in gadgetFiles:
            if 'arm64' in gadgetFile:
                fullPath = os.path.join(targetFolder, gadgetFile)
                ret = fullPath
                break

    elif abi is 'x86':
        for gadgetFile in gadgetFiles:
            if 'i386' in gadgetFile:
                fullPath = os.path.join(targetFolder, gadgetFile)
                ret = fullPath
                break

    elif abi is 'x86_64':
        for gadgetFile in gadgetFiles:
            if 'x86_64' in gadgetFile:
                fullPath = os.path.join(targetFolder, gadgetFile)
                ret = fullPath
                break
    
    if ret is None:
        sys.stdout.write('[-] No recommended gadget file was found.\n')
    else:
        sys.stdout.write('[*] Architecture identified (%s). Gadget was selected.\n' %(abi))

    return ret

def selectInteractionType():
    print '[*] INTERACTION TYPE'
    print '1 - Listen'
    print '2 - Script'
    # print '3 - ScriptDirectory' ## Not supported yet
    
    code = raw_input('\nSelect an interaction type (Default: Listen): ')

    if code not in ['1', '2']:
        code = '1'

    if code == '1':
        print '\n[+] Type "listen" was selected...'
        return 'listen'
    elif code == '2':
        print '\n[+] Type "Script" was selected...'
        return 'script'

def getListenConfigs():
    address = raw_input('\nAddress to listen (Default: 127.0.0.1): ')

    if address == '':
        address = '127.0.0.1'

    port = raw_input('\nPort to listen (Default: 27042): ')

    if port == '':
        port = 27042
    else:
        port = int(port)

    on_load = raw_input('\nWhat to do when start app (Default: wait): ')

    if on_load == '':
        on_load = 'wait'

    return address, port, on_load

def saveConfigFile(configText):
    filePath = os.path.join(os.getcwd(), 'apkpatcher_config.config')
    f = open(filePath, 'w')

    f.write(configText)
    f.close()

    print '[+] The config file was created at %s' %(filePath)

def configWizard():
    print '+---------------------------------+'
    print '|          CONFIG WIZARD          |'
    print '+---------------------------------+\n\n'
    
    config = {}
    interactionType = selectInteractionType()

    if interactionType == 'listen':
        address, port, on_load = getListenConfigs()
        
        config['interaction'] = {
            'type': interactionType,
            'address': address,
            'port': port,
            'on_load': on_load
        }

    elif interactionType == 'script':
        path = raw_input('\nPath of the hook file on the device (Default: ./hook.js): ')

        if path == '':
            path = './hook.js'

        config['interaction'] = {
            'type': interactionType,
            'path': path
        }
        
    configText = str(json.dumps(config))

    saveConfigFile(configText)

def getIntFridaVersion(version):
    versionSplit = version.split('.')

    if(len(versionSplit) > 3):
        versionSplit = versionSplit[0:3]

    while(len(versionSplit) < 3):
        versionSplit.append('0')

    return int(''.join(["{num:03d}".format(num=int(i)) for i in versionSplit]))
    
def minFridaVersion(minVersion):
    fridaVersion = subprocess.check_output(['frida', '--version']).strip()

    if getIntFridaVersion(fridaVersion) < getIntFridaVersion(minVersion):
        return False

    return True
    
def getDefaultConfigFile():
    config = '''
{
    "interaction": {
        "type": "script",
        "path": "./libhook.js.so"
    }
}
    '''
    
    path = os.path.join(os.getcwd(), 'generatedConfigFile.config')
    f = open(path, 'w')

    f.write(config)
    f.close()

    return path
    
def main():
    parser = argparse.ArgumentParser()

    parser.add_argument('-a', '--apk', help='Specify the apk you want to patch')
    #parser.add_argument('-l', '--list', help='List the available frida-gadgets')
    parser.add_argument('-g', '--gadget', help='Specify the frida-gadget file')
    parser.add_argument('--update', help='Update frida-gadgets', action='store_true')
    parser.add_argument('--config-wizard', help='A wizard to create config files', action='store_true')
    parser.add_argument('--autoload-script', help='Autoload hook script when start the app')
    parser.add_argument('--config-file', help='Specify the config file to the gadget')
    
    args = parser.parse_args()
    
    if len(sys.argv) == 1:
        parser.print_help()
        return
    
    if args.update:
        updateFridaGadgets()

    if args.config_wizard:
        configWizard()
        return

    if not args.apk:
        parser.print_help()
        return
    
    if args.autoload_script and args.config_file:
        sys.stdout.write(bcolors.FAIL + '[-] Do not use --autoload-script and --config together.\n' + bcolors.ENDC)
        exit(1)
    
    configFile = ''
    if args.autoload_script:
        if not minFridaVersion('10.6.33'):
            sys.stdout.write(bcolors.FAIL + '[-] Autoload is not supported in this version of frida. Update your frida!\n' + bcolors.ENDC)
            exit(1)
            
        configFile = getDefaultConfigFile()

    if args.config_file:
        if not minFridaVersion('10.6.33'):
            sys.stdout.write(bcolors.FAIL + '[-] Config file is not supported in this version of frida. Update your frida!\n' + bcolors.ENDC)
            exit(1)
            
        configFile = os.path.join(os.getcwd(), args.config_file)
    
    if args.apk:
        if not hasSatisfiedDependencies():
            exit(1)

        if args.gadget:
            fridaGadgetFile = args.gadget
        else:
            fridaGadgetFile = getRecommendedGadget()

            if fridaGadgetFile is None:
                sys.stdout.write(bcolors.FAIL + '[-] Could not identify the right frida-gadget file.\n' + bcolors.ENDC)
                sys.stdout.write(bcolors.FAIL + '[!] Is your smartphone connected?\n' + bcolors.ENDC)
                exit(1)

        patchApk(args.apk, fridaGadgetFile, configFile, args.autoload_script)
            
if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print bcolors.FAIL + '[-] CTRL+C was pressed. Exiting...' + bcolors.ENDC
        exit(1)
